In [18]:
#Extract packages
import pandas as pd
import numpy as np

In [28]:
#Extract dataset
df = pd.read_csv('https://raw.githubusercontent.com/HumayDS/Digital-Data-Analytics-E-15-24/refs/heads/main/clv.csv')

In [29]:
df.head()

,customer_id,first_purchase_date,last_purchase_date,total_orders,total_revenue
0,C001,2023-01-10,2023-03-15,5,250
1,C002,2023-02-05,2023-02-20,2,80
2,C003,2023-01-20,2023-06-10,10,900
3,C004,2023-03-01,2023-03-05,1,30
4,C005,2023-01-15,2023-04-20,6,300

#CLV - Customer lifetime value

##Customer Lifetime Value (CLV) is the total amount of revenue or profit a business expects to earn from a single customer over the entire duration of their relationship.
##CLV answers the question: “How much money will this customer bring to the business over time?”
##CLV is mainly driven by:
##Average Order Value (AOV) – how much a customer spends per purchase
##Purchase Frequency – how often they buy
##Customer Lifespan – how long they stay a customer

#CLV=Average Order Value×Purchase Frequency×Customer Lifespan

Example:

A customer spends $20 per purchase

Buys 2 times per month

Stays for 12 months

CLV = 20 × 2 × 12 = $480

Why CLV matters:

Helps determine how much you can spend on acquiring a customer

Identifies high-value customer segments

Supports retention strategies

Improves profitability analysis

In [30]:
# Recommendable check NA, outlier(describe(), and data types before analysing. )
#check if there is any na
df.isnull().sum()

customer_id            0
first_purchase_date    0
last_purchase_date     0
total_orders           0
total_revenue          0
dtype: int64

In [ ]:
#df = df.dropna()

In [32]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
total_orders,60.0,5.016667,3.427168,1.0,2.00,4.5,8.0,12.0
total_revenue,60.0,383.950000,381.303492,20.0,83.75,225.0,645.0,1400.0

In [33]:
# Convert date columns to datetime format
df['first_purchase_date'] = pd.to_datetime(df['first_purchase_date'])
df['last_purchase_date'] = pd.to_datetime(df['last_purchase_date'])

In [35]:
# Calculate customer lifetime in days
# The total number of days the customer has been with us.
df['customer_lifetime'] = (df['last_purchase_date'] - df['first_purchase_date']).dt.days

In [36]:
# Calculate purchase frequency
#The average number of purchases a customer makes per day.
df['purchase_frequency'] = df['total_orders'] / df['customer_lifetime']

df

,customer_id,first_purchase_date,last_purchase_date,total_orders,total_revenue,customer_lifetime,purchase_frequency
0,C001,2023-01-10,2023-03-15,5,250,64,0.078125
1,C002,2023-02-05,2023-02-20,2,80,15,0.133333
2,C003,2023-01-20,2023-06-10,10,900,141,0.070922
3,C004,2023-03-01,2023-03-05,1,30,4,0.250000
4,C005,2023-01-15,2023-04-20,6,300,95,0.063158
5,C006,2023-02-10,2023-02-12,1,20,2,0.500000
6,C007,2023-01-05,2023-07-01,12,1200,177,0.067797
7,C008,2023-03-12,2023-04-01,3,150,20,0.150000
8,C009,2023-02-18,2023-05-30,7,500,101,0.069307
9,C010,2023-01-25,2023-01-30,2,60,5,0.400000
10,C011,2023-02-01,2023-06-01,8,640,120,0.066667
11,C012,2023-03-10,2023-03-15,1,25,5,0.200000
12,C013,2023-01-08,2023-04-10,5,275,92,0.054348
13,C014,2023-02-20,2023-06-25,9,810,125,0.072000
14,C015,2023-01-18,2023-02-01,2,70,14,0.142857
15,C016,2023-01-12,2023-05-20,7,490,128,0.054688
16,C017,2023-02-14,2023-03-10,3,120,24,0.125000
17,C018,2023-01-03,2023-07-10,11,1150,188,0.058511
18,C019,2023-03-05,2023-04-15,4,200,41,0.097561
19,C020,2023-02-25,2023-03-05,1,35,8,0.125000
20,C021,2023-01-07,2023-06-18,9,780,162,0.055556
21,C022,2023-03-15,2023-04-05,2,90,21,0.095238
22,C023,2023-02-02,2023-05-25,6,420,112,0.053571
23,C024,2023-01-28,2023-02-02,1,40,5,0.200000
24,C025,2023-01-11,2023-07-02,10,950,172,0.058140
25,C026,2023-02-17,2023-03-01,2,85,12,0.166667
26,C027,2023-01-09,2023-04-30,6,360,111,0.054054
27,C028,2023-03-03,2023-03-20,2,75,17,0.117647
28,C029,2023-02-22,2023-06-15,8,700,113,0.070796
29,C030,2023-01-16,2023-02-10,3,110,25,0.120000
30,C031,2023-01-04,2023-07-05,12,1300,182,0.065934
31,C032,2023-02-08,2023-03-12,2,95,32,0.062500
32,C033,2023-01-21,2023-05-10,7,520,109,0.064220
33,C034,2023-03-06,2023-03-18,1,28,12,0.083333
34,C035,2023-01-14,2023-06-28,9,840,165,0.054545
35,C036,2023-02-12,2023-02-25,2,88,13,0.153846
36,C037,2023-01-06,2023-04-25,5,310,109,0.045872
37,C038,2023-03-08,2023-04-02,3,140,25,0.120000
38,C039,2023-02-28,2023-06-05,8,660,97,0.082474
39,C040,2023-01-19,2023-02-05,2,65,17,0.117647
40,C041,2023-01-02,2023-07-08,11,1180,187,0.058824
41,C042,2023-02-09,2023-03-15,3,130,34,0.088235
42,C043,2023-01-23,2023-05-18,6,450,115,0.052174
43,C044,2023-03-02,2023-03-10,1,22,8,0.125000
44,C045,2023-01-17,2023-06-22,9,790,156,0.057692
45,C046,2023-02-13,2023-02-28,2,92,15,0.133333
46,C047,2023-01-05,2023-04-28,5,330,113,0.044248
47,C048,2023-03-11,2023-04-05,3,155,25,0.120000
48,C049,2023-02-26,2023-06-12,7,610,106,0.066038
49,C050,2023-01-20,2023-02-03,2,75,14,0.142857
50,C051,2023-01-01,2023-07-12,12,1400,192,0.062500
51,C052,2023-02-07,2023-03-14,3,135,35,0.085714
52,C053,2023-01-22,2023-05-12,6,470,110,0.054545
53,C054,2023-03-04,2023-03-16,1,27,12,0.083333
54,C055,2023-01-13,2023-06-30,10,920,168,0.059524
55,C056,2023-02-15,2023-02-27,2,90,12,0.166667
56,C057,2023-01-10,2023-04-22,5,305,102,0.049020
57,C058,2023-03-09,2023-04-03,3,145,25,0.120000
58,C059,2023-02-27,2023-06-08,8,680,101,0.079208
59,C060,2023-01-24,2023-02-06,2,70,13,0.153846

In [37]:
# Calculate average order value
#AOV (Average Order Value) calculates how much a customer spends on average per order.
df['average_order_value'] = df['total_revenue'] / df['total_orders']

In [43]:
segment_counts = df['segment'].value_counts().sort_index()
print(segment_counts)# calculates Customer Lifetime Value (CLV) for each customer.
#This represents the total revenue a business can expect from a customer over their lifetime.
df['CLV'] = (
    df['average_order_value'] *
    df['purchase_frequency'] *
    df['customer_lifetime']
)

df

,customer_id,first_purchase_date,last_purchase_date,total_orders,total_revenue,customer_lifetime,purchase_frequency,average_order_value,CLV,segment
0,C001,2023-01-10,2023-03-15,5,250,64,0.078125,50.000000,250.0,Medium
1,C002,2023-02-05,2023-02-20,2,80,15,0.133333,40.000000,80.0,Low
2,C003,2023-01-20,2023-06-10,10,900,141,0.070922,90.000000,900.0,High
3,C004,2023-03-01,2023-03-05,1,30,4,0.250000,30.000000,30.0,Low
4,C005,2023-01-15,2023-04-20,6,300,95,0.063158,50.000000,300.0,Medium
5,C006,2023-02-10,2023-02-12,1,20,2,0.500000,20.000000,20.0,Low
6,C007,2023-01-05,2023-07-01,12,1200,177,0.067797,100.000000,1200.0,High
7,C008,2023-03-12,2023-04-01,3,150,20,0.150000,50.000000,150.0,Medium
8,C009,2023-02-18,2023-05-30,7,500,101,0.069307,71.428571,500.0,High
9,C010,2023-01-25,2023-01-30,2,60,5,0.400000,30.000000,60.0,Low
10,C011,2023-02-01,2023-06-01,8,640,120,0.066667,80.000000,640.0,High
11,C012,2023-03-10,2023-03-15,1,25,5,0.200000,25.000000,25.0,Low
12,C013,2023-01-08,2023-04-10,5,275,92,0.054348,55.000000,275.0,Medium
13,C014,2023-02-20,2023-06-25,9,810,125,0.072000,90.000000,810.0,High
14,C015,2023-01-18,2023-02-01,2,70,14,0.142857,35.000000,70.0,Low
15,C016,2023-01-12,2023-05-20,7,490,128,0.054688,70.000000,490.0,High
16,C017,2023-02-14,2023-03-10,3,120,24,0.125000,40.000000,120.0,Medium
17,C018,2023-01-03,2023-07-10,11,1150,188,0.058511,104.545455,1150.0,High
18,C019,2023-03-05,2023-04-15,4,200,41,0.097561,50.000000,200.0,Medium
19,C020,2023-02-25,2023-03-05,1,35,8,0.125000,35.000000,35.0,Low
20,C021,2023-01-07,2023-06-18,9,780,162,0.055556,86.666667,780.0,High
21,C022,2023-03-15,2023-04-05,2,90,21,0.095238,45.000000,90.0,Low
22,C023,2023-02-02,2023-05-25,6,420,112,0.053571,70.000000,420.0,Medium
23,C024,2023-01-28,2023-02-02,1,40,5,0.200000,40.000000,40.0,Low
24,C025,2023-01-11,2023-07-02,10,950,172,0.058140,95.000000,950.0,High
25,C026,2023-02-17,2023-03-01,2,85,12,0.166667,42.500000,85.0,Low
26,C027,2023-01-09,2023-04-30,6,360,111,0.054054,60.000000,360.0,Medium
27,C028,2023-03-03,2023-03-20,2,75,17,0.117647,37.500000,75.0,Low
28,C029,2023-02-22,2023-06-15,8,700,113,0.070796,87.500000,700.0,High
29,C030,2023-01-16,2023-02-10,3,110,25,0.120000,36.666667,110.0,Medium
30,C031,2023-01-04,2023-07-05,12,1300,182,0.065934,108.333333,1300.0,High
31,C032,2023-02-08,2023-03-12,2,95,32,0.062500,47.500000,95.0,Medium
32,C033,2023-01-21,2023-05-10,7,520,109,0.064220,74.285714,520.0,High
33,C034,2023-03-06,2023-03-18,1,28,12,0.083333,28.000000,28.0,Low
34,C035,2023-01-14,2023-06-28,9,840,165,0.054545,93.333333,840.0,High
35,C036,2023-02-12,2023-02-25,2,88,13,0.153846,44.000000,88.0,Low
36,C037,2023-01-06,2023-04-25,5,310,109,0.045872,62.000000,310.0,Medium
37,C038,2023-03-08,2023-04-02,3,140,25,0.120000,46.666667,140.0,Medium
38,C039,2023-02-28,2023-06-05,8,660,97,0.082474,82.500000,660.0,High
39,C040,2023-01-19,2023-02-05,2,65,17,0.117647,32.500000,65.0,Low
40,C041,2023-01-02,2023-07-08,11,1180,187,0.058824,107.272727,1180.0,High
41,C042,2023-02-09,2023-03-15,3,130,34,0.088235,43.333333,130.0,Medium
42,C043,2023-01-23,2023-05-18,6,450,115,0.052174,75.000000,450.0,Medium
43,C044,2023-03-02,2023-03-10,1,22,8,0.125000,22.000000,22.0,Low
44,C045,2023-01-17,2023-06-22,9,790,156,0.057692,87.777778,790.0,High
45,C046,2023-02-13,2023-02-28,2,92,15,0.133333,46.000000,92.0,Low
46,C047,2023-01-05,2023-04-28,5,330,113,0.044248,66.000000,330.0,Medium
47,C048,2023-03-11,2023-04-05,3,155,25,0.120000,51.666667,155.0,Medium
48,C049,2023-02-26,2023-06-12,7,610,106,0.066038,87.142857,610.0,High
49,C050,2023-01-20,2023-02-03,2,75,14,0.142857,37.500000,75.0,Low
50,C051,2023-01-01,2023-07-12,12,1400,192,0.062500,116.666667,1400.0,High
51,C052,2023-02-07,2023-03-14,3,135,35,0.085714,45.000000,135.0,Medium
52,C053,2023-01-22,2023-05-12,6,470,110,0.054545,78.333333,470.0,Medium
53,C054,2023-03-04,2023-03-16,1,27,12,0.083333,27.000000,27.0,Low
54,C055,2023-01-13,2023-06-30,10,920,168,0.059524,92.000000,920.0,High
55,C056,2023-02-15,2023-02-27,2,90,12,0.166667,45.000000,90.0,Low
56,C057,2023-01-10,2023-04-22,5,305,102,0.049020,61.000000,305.0,Medium
57,C058,2023-03-09,2023-04-03,3,145,25,0.120000,48.333333,145.0,Medium
58,C059,2023-02-27,2023-06-08,8,680,101,0.079208,85.000000,680.0,High
59,C060,2023-01-24,2023-02-06,2,70,13,0.153846,35.000000,70.0,Low

In [48]:
segment_counts = df['segment'].value_counts().sort_index()
print(segment_counts)

segment
Low       20
Medium    20
High      20
Name: count, dtype: int64

In [44]:
#This line segments customers into three groups based on their CLV values using quantile-based binning.
df['segment'] = pd.qcut(df['CLV'], q=3, labels=['Low', 'Medium', 'High'])

In [46]:
df

,customer_id,first_purchase_date,last_purchase_date,total_orders,total_revenue,customer_lifetime,purchase_frequency,average_order_value,CLV,segment
0,C001,2023-01-10,2023-03-15,5,250,64,0.078125,50.000000,250.0,Medium
1,C002,2023-02-05,2023-02-20,2,80,15,0.133333,40.000000,80.0,Low
2,C003,2023-01-20,2023-06-10,10,900,141,0.070922,90.000000,900.0,High
3,C004,2023-03-01,2023-03-05,1,30,4,0.250000,30.000000,30.0,Low
4,C005,2023-01-15,2023-04-20,6,300,95,0.063158,50.000000,300.0,Medium
5,C006,2023-02-10,2023-02-12,1,20,2,0.500000,20.000000,20.0,Low
6,C007,2023-01-05,2023-07-01,12,1200,177,0.067797,100.000000,1200.0,High
7,C008,2023-03-12,2023-04-01,3,150,20,0.150000,50.000000,150.0,Medium
8,C009,2023-02-18,2023-05-30,7,500,101,0.069307,71.428571,500.0,High
9,C010,2023-01-25,2023-01-30,2,60,5,0.400000,30.000000,60.0,Low
10,C011,2023-02-01,2023-06-01,8,640,120,0.066667,80.000000,640.0,High
11,C012,2023-03-10,2023-03-15,1,25,5,0.200000,25.000000,25.0,Low
12,C013,2023-01-08,2023-04-10,5,275,92,0.054348,55.000000,275.0,Medium
13,C014,2023-02-20,2023-06-25,9,810,125,0.072000,90.000000,810.0,High
14,C015,2023-01-18,2023-02-01,2,70,14,0.142857,35.000000,70.0,Low
15,C016,2023-01-12,2023-05-20,7,490,128,0.054688,70.000000,490.0,High
16,C017,2023-02-14,2023-03-10,3,120,24,0.125000,40.000000,120.0,Medium
17,C018,2023-01-03,2023-07-10,11,1150,188,0.058511,104.545455,1150.0,High
18,C019,2023-03-05,2023-04-15,4,200,41,0.097561,50.000000,200.0,Medium
19,C020,2023-02-25,2023-03-05,1,35,8,0.125000,35.000000,35.0,Low
20,C021,2023-01-07,2023-06-18,9,780,162,0.055556,86.666667,780.0,High
21,C022,2023-03-15,2023-04-05,2,90,21,0.095238,45.000000,90.0,Low
22,C023,2023-02-02,2023-05-25,6,420,112,0.053571,70.000000,420.0,Medium
23,C024,2023-01-28,2023-02-02,1,40,5,0.200000,40.000000,40.0,Low
24,C025,2023-01-11,2023-07-02,10,950,172,0.058140,95.000000,950.0,High
25,C026,2023-02-17,2023-03-01,2,85,12,0.166667,42.500000,85.0,Low
26,C027,2023-01-09,2023-04-30,6,360,111,0.054054,60.000000,360.0,Medium
27,C028,2023-03-03,2023-03-20,2,75,17,0.117647,37.500000,75.0,Low
28,C029,2023-02-22,2023-06-15,8,700,113,0.070796,87.500000,700.0,High
29,C030,2023-01-16,2023-02-10,3,110,25,0.120000,36.666667,110.0,Medium
30,C031,2023-01-04,2023-07-05,12,1300,182,0.065934,108.333333,1300.0,High
31,C032,2023-02-08,2023-03-12,2,95,32,0.062500,47.500000,95.0,Medium
32,C033,2023-01-21,2023-05-10,7,520,109,0.064220,74.285714,520.0,High
33,C034,2023-03-06,2023-03-18,1,28,12,0.083333,28.000000,28.0,Low
34,C035,2023-01-14,2023-06-28,9,840,165,0.054545,93.333333,840.0,High
35,C036,2023-02-12,2023-02-25,2,88,13,0.153846,44.000000,88.0,Low
36,C037,2023-01-06,2023-04-25,5,310,109,0.045872,62.000000,310.0,Medium
37,C038,2023-03-08,2023-04-02,3,140,25,0.120000,46.666667,140.0,Medium
38,C039,2023-02-28,2023-06-05,8,660,97,0.082474,82.500000,660.0,High
39,C040,2023-01-19,2023-02-05,2,65,17,0.117647,32.500000,65.0,Low
40,C041,2023-01-02,2023-07-08,11,1180,187,0.058824,107.272727,1180.0,High
41,C042,2023-02-09,2023-03-15,3,130,34,0.088235,43.333333,130.0,Medium
42,C043,2023-01-23,2023-05-18,6,450,115,0.052174,75.000000,450.0,Medium
43,C044,2023-03-02,2023-03-10,1,22,8,0.125000,22.000000,22.0,Low
44,C045,2023-01-17,2023-06-22,9,790,156,0.057692,87.777778,790.0,High
45,C046,2023-02-13,2023-02-28,2,92,15,0.133333,46.000000,92.0,Low
46,C047,2023-01-05,2023-04-28,5,330,113,0.044248,66.000000,330.0,Medium
47,C048,2023-03-11,2023-04-05,3,155,25,0.120000,51.666667,155.0,Medium
48,C049,2023-02-26,2023-06-12,7,610,106,0.066038,87.142857,610.0,High
49,C050,2023-01-20,2023-02-03,2,75,14,0.142857,37.500000,75.0,Low
50,C051,2023-01-01,2023-07-12,12,1400,192,0.062500,116.666667,1400.0,High
51,C052,2023-02-07,2023-03-14,3,135,35,0.085714,45.000000,135.0,Medium
52,C053,2023-01-22,2023-05-12,6,470,110,0.054545,78.333333,470.0,Medium
53,C054,2023-03-04,2023-03-16,1,27,12,0.083333,27.000000,27.0,Low
54,C055,2023-01-13,2023-06-30,10,920,168,0.059524,92.000000,920.0,High
55,C056,2023-02-15,2023-02-27,2,90,12,0.166667,45.000000,90.0,Low
56,C057,2023-01-10,2023-04-22,5,305,102,0.049020,61.000000,305.0,Medium
57,C058,2023-03-09,2023-04-03,3,145,25,0.120000,48.333333,145.0,Medium
58,C059,2023-02-27,2023-06-08,8,680,101,0.079208,85.000000,680.0,High
59,C060,2023-01-24,2023-02-06,2,70,13,0.153846,35.000000,70.0,Low

In [47]:
segment_analysis = df.groupby('segment').agg({
    'CLV': 'mean',
    'total_orders': 'mean',
    'total_revenue': 'mean',
    'customer_lifetime': 'mean',
    'purchase_frequency': 'mean'
}).round(2)

segment_analysis

/tmp/ipykernel_333/930912433.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  segment_analysis = df.groupby('segment').agg({

,CLV,total_orders,total_revenue,customer_lifetime,purchase_frequency
segment,,,,,
Low,58.35,1.60,58.35,11.20,0.17
Medium,242.50,4.25,242.50,65.45,0.08
High,851.00,9.20,851.00,144.50,0.06

#Interesting insight :
##Best customers are not frequent — they are long-term

CLV ↑ increases mainly due to lifetime and the number of orders.

As we move from Low → High:

Orders: 1.6 → 9.2
Lifetime: 11 → 144 days
 This means:
The main driver of CLV growth is not frequency, but longevity + order count.

Interesting and critical finding ❗

Purchase frequency DECREASES:

Low: 0.17
Medium: 0.08
High: 0.06

What does this mean?

High-value customers do not purchase frequently.

However, they stay longer and place more orders over time.
They are loyal, but not impulsive.

### Low CLV

Short-term, few orders

They come quickly and leave quickly
 Retention problem

### Medium CLV

Moderate behavior, stable customers
Upsell / growth potential

###High CLV

Stay for a long time, place many orders

But purchase frequency is low
Loyal customers, but need activation